name: Optional dependencies (mirage-xen mirage-solo5)

on: [push, pull_request]

jobs:
  tests:
    name: Tests

    strategy:
      fail-fast: false
      matrix:
        ocaml-version: ["4.14.2"]
        operating-system: [ubuntu-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - name: Install dependencies
        run: opam install --deps-only -t .

      - name: Install optional dependencies
        run: opam install mirage-solo5 mirage-xen

      - name: Build
        run: opam exec -- dune build @all

      - name: Test
        run: opam exec -- dune runtest
